version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: tel_project_db
      POSTGRES_PASSWORD: 'TheP@SsW0rdPle@s$$'
